name: local_hero_transform
description: "LocalHeroTransform is a powerful Flutter package designed to simplify the creation of seamless transitions between items in grid and list views. By leveraging local hero animations, this package enhances the visual appeal of your app while providing a smooth user experience."
version: 0.0.1
homepage: https://github.com/najeebaslan/local_hero_transform.git

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


 

flutter:
